### ISSUE TITLE
Выполнить до 15.05.23

### ISSUE THREAD

**Issue by MunSunch** [MunSunch/DigDes#1]
1) Реализовать некий dataStorage для хранения сущности (можно одной, например сотрудника) в файле
     - Требования к структуре хранения нет. как к структуре файлов, так и к содержимому (массив байтов, json, xml, какой то свой формат в строках, и т.д)
     - методы create, update, getById, getAll, deleteById
     - для работы с файлами использовать  java.io, java.nio
     - выделить интерфейс репозитория, описанный dataStorage должен быть его реализацией
     - jpa подключать не нужно, сервисы и контроллеры реализовывать не нужно (можно по одному для отладки)

2) Заполнить Model сущностями(можно только сотрудника). Без JPA!!!
3) Разработать DTO:
    * DTO на вход операций описанных в ТЗ
    * DTO на выход операций описанных в ТЗ

**Comment by Nagibator9999** [comment]
Я займусь

**Comment by MunSunch** [comment]
твой код никуда не годится, придется делать самому
